# PGUSER=postgres PGPASSWORD=carltonlasiter heroku pg:pull DATABASE_URL c4t_dev --app sequimgym

development:
  adapter: postgresql
  encoding: unicode
  database: c4t_dev
  pool: 5
  host: localhost
  port: 5432
  username: postgres
  password: carltonlasiter

test:
  adapter: postgresql
  encoding: unicode
  database: c4t_test
  pool: 5
  host: localhost
  port: 5432
  username: postgres
  password: carltonlasiter

production:
  adapter: postgresql
  encoding: unicode
  database: c4t_production
  pool: 5
  password:
